apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: angular-tour-of-heroes
  description: My own angular project on Github
  labels:
    example.com/custom: custom_label_value
  annotations:
    github.com/project-slug: oconnormj/angular-tour-of-heroes
    example.com/service-discovery: artistweb
    circleci.com/project-slug: github/example-org/artist-website
  tags:
    - angular
  links:
    - url: https://admin.example-org.com
      title: Admin Dashboard
      icon: dashboard
      type: admin-dashboard
spec:
  type: website
  lifecycle: production
  owner: team-a
